server:
  port: 8082 # 修改
spring:
  application:
    name: cart-service
  spring:
    cloud:
      nacos:
        server-addr: localhost:8848
  profiles:
    active: dev
  datasource:
    # 修改 database
    url: jdbc:mysql://${hm.db.host}:3306/hm-cart?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    # 修改
    title: 购物车服务接口文档
    description: "购物车服务接口文档"
    email: downey.mzh@gmail.com
    concat: DowneyM
    url: https://downey.top
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.cart.controller # 修改